apiVersion: v1
kind: ServiceAccount
metadata:
  name: visa-processor
  namespace: payments
  labels:
    app: visa-processor
---
# Deployment named "visa-processor"
# Listens on :8080
# Vulnerable to struts
# Has SSH keys mounted
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visa-processor
  namespace: payments
  labels:
    app: visa-processor
    app.kubernetes.io/part-of: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visa-processor
  template:
    metadata:
      labels:
        app: visa-processor
    spec:
      containers:
        - image: quay.io/vuln/rce-webapp:latest
          command: ["/bin/entrypoint"]
          args:
            [
              "-listen",
              ":8080",
            ]
          imagePullPolicy: Always
          name: visa-processor
          ports:
            - containerPort: 22
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          env:
            - name: exploit
              value: "true"
---
# Service named "visa-processor-service"
# Listens on :8080
apiVersion: v1
kind: Service
metadata:
  labels:
    app: visa-processor
  name: visa-processor-service
  namespace: payments
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: visa-processor
  type: ClusterIP